### ISSUE TITLE
"Access to the path is denied." During patching

### ISSUE THREAD

**Issue by JulesThuillier** [yasirkula/UnitySimplePatchTool#10]
Hello all !

I have followed the steps closely, uploaded my initial version to **Google Drive**, then created a patch, uploaded it (and updated Download links before).
But when I start my application to test the update (using SelfPatchingAppDemo Scene as first scene), I run into the following error :

```...Retrieving version info...
...Checking if files are up-to-date...
Preferred patch method RepairPatch: 0.00MB
Preferred patch method InstallerPatch: 39.61MB
Applying repair patch
...Calculating new or changed files...
...Checking if files are up-to-date...
...Calculating obsolete files...
...No obsolete files...
System.UnauthorizedAccessException: Access to the path is denied.
  at System.IO.Directory.Move (System.String sourceDirName, System.String destDirName) [0x000dd] in <437ba245d8404784b9fbab9b439ac908>:0 
  at SimplePatchToolCore.PatchUtils.MoveDirectory (System.String fromAbsolutePath, System.String toAbsolutePath) [0x00034] in <d68e525fd4df44baa2dff0c30ea1a517>:0 
  at SimplePatchToolCore.SimplePatchTool.Patch () [0x00a63] in <d68e525fd4df44baa2dff0c30ea1a517>:0 
  at SimplePatchToolCore.SimplePatchTool.ThreadPatchFunction () [0x00016] in <d68e525fd4df44baa2dff0c30ea1a517>:0 
```

I have tried to look into the code but it seems the **Move** function is called from the dll only.
I also tried running my app as an **Administrator** with no luck... 
Any ideas ?

**Comment by yasirkula** [comment]
It goes from [here](https://github.com/yasirkula/SimplePatchTool/blob/cfd2c3697cda5b3167cf50402cba392e13abcfca/SimplePatchToolCore/Core/SimplePatchTool.cs#L826-L830) to [here](https://github.com/yasirkula/SimplePatchTool/blob/cfd2c3697cda5b3167cf50402cba392e13abcfca/SimplePatchToolCore/Utilities/PatchUtils.cs#L312-L321). I couldn't see any issues at those lines so I googled the issue. Seems like there are two possible reasons for it: 1) open file handles and 2) [this](https://stackoverflow.com/a/47202660/2373034). If this issue happens all the time in your case, I'll apply the second solution and send it to you to see if it works. If this issue happened only once and is not happening anymore, then I'll continue guessing how to resolve the issue.

**Comment by JulesThuillier** [comment]
Hi @yasirkula ! Thank you for that fast anwser !
I have that issue all the time (I just tried after a reboot in case). The thing is is that I don't know which folder cause this problem, a Log here could help I guess. I have been looking on Stackoverflow but did not anything very relevant. The path of the files being moved are only within the Unity game folder right ?

**Comment by yasirkula** [comment]
Try replacing SimplePatchTool.dll with the one inside this archive: [SimplePatchTool.zip](https://github.com/yasirkula/UnitySimplePatchTool/files/4374475/SimplePatchTool.zip). Hope it works ^^

**Comment by JulesThuillier** [comment]
I don't know what you did, but it is a big **SUCCESS !!!** 
Thanks a lot !

**Comment by yasirkula** [comment]
Glad to hear it! I'll update the plugin on Asset Store soon.
