### ISSUE TITLE
Slow compression

### ISSUE THREAD

**Issue by FreezerJohn** [yasirkula/UnitySimplePatchTool#3]
I'm not sure if this a bug or normal behavior, but the compression speeds I get are very low at around ~350kB/s on an i5 gen 6.

This is measured during the creation of an incremental patch through the SimplePatchTool window inside unity. I'm aware it utilizes only a single core, but this still seems slow. My understanding is that the diff-stage is completed when compression starts, so this should not influence the speed at that point.
I haven't looked further into it, but my guess would be there is an unintended overhead introduced while using the compression lib.

**Comment by yasirkula** [comment]
Yes, unfortunately the LZMA SDK is the bottleneck here. See a discussion about it: https://stackoverflow.com/questions/12292593/why-is-lzma-sdk-7-zip-so-slow

If there's a way to speed up this process, I'm happy to implement it.

**Comment by FreezerJohn** [comment]
I see.. so looks like there is no way around using a natively compiled lib, either the 7z or QuickLZ like they suggested. I guess this would make the multi platform support more complicated. But may be still worth to look into.

**Comment by FreezerJohn** [comment]
I just noticed that the dlls included on the asset store might be build in debug mode. When build in release mode, I get more than double the compression speed!

**Comment by yasirkula** [comment]
They're built using `Release/Any CPU` configuration on Windows 10 (64-bit). Did you change any other settings in the SimplePatchTool solution/project?

**Comment by FreezerJohn** [comment]
Okay, well I actually only tested the command line tool. But the speed in Unity is similar to the one I get with the command line tool and lib build in Debug mode. In other words, without any changes the command line tool is twice as fast as the unity port. I don't understand why that is, as the unity editor script just calls the lib right?

**Comment by yasirkula** [comment]
Yes, the editor script just calls the lib but while the console app uses .NET, Unity editor script uses Mono. Seems like compression runs slower on Mono than on .NET.

**Comment by FreezerJohn** [comment]
Ah of course, that makes sense!

**Comment by yasirkula** [comment]
The latest release adds GZIP and NONE compression methods which should be faster than LZMA compression.
