### ISSUE TITLE
Update always gets stuck on downloading sharedAssets file

### ISSUE THREAD

**Issue by OagDevelop** [yasirkula/UnitySimplePatchTool#4]
I am storing all the files on my local machine so the problem is not due to timing out.

The patch that I am struggling with does have some very large files (almost 6GB)

The Error on the Launcher is "ERROR: patch 0_2__0_3 could not be downloaded"
It does hang up on the large 6GB file before showing the error.

**Comment by yasirkula** [comment]
Sorry to hear that. Assuming the `file://` download url of the patch is correct, can you insert some Debug.Log messages [here](https://github.com/yasirkula/UnitySimplePatchTool/blob/98c92a1ceca11e60c7f2186182fc3dd527492d08/Plugins/SimplePatchTool/Scripts/CookieAwareWebClient.cs#L259-L324) to see where the execution is interrupted or if the error is null? You can use this asset to see debug messages at runtime: https://github.com/yasirkula/UnityIngameDebugConsole

**Comment by OagDevelop** [comment]
so it doesnt appear to make it into 
"if( !cancelled )...." on line 297.  
_webOp.Cancelled and webRequest.isError are coming up as true.

**Comment by yasirkula** [comment]
What does webRequest.error say?

**Comment by OagDevelop** [comment]
The error appears to be null. When i log the  webRequest.error.toString() it stops the launcher running.

![weberror](https://user-images.githubusercontent.com/29358801/51387643-c9b5fb80-1af4-11e9-936a-1f4813cde161.PNG)

**Comment by OagDevelop** [comment]
I should add that i am not using a server right now. I am just using Filepaths on my computer.

**Comment by yasirkula** [comment]
Using file paths is fine. Can I see the modified parts of the CookieAwareWebClient.cs?

**Comment by OagDevelop** [comment]
![image](https://user-images.githubusercontent.com/29358801/51393052-c88cca80-1b04-11e9-9742-1c1edf0392b8.png)

**Comment by yasirkula** [comment]
You have some nice Debug.Logs there 😺 Try putting log 321 inside an `if(webRequest.isNetworkError)` statement and removing the ToString() from the error.

**Comment by OagDevelop** [comment]
Request aborted

![image](https://user-images.githubusercontent.com/29358801/51397058-60db7d00-1b0e-11e9-90fb-a20a5f73371a.png)

**Comment by yasirkula** [comment]
Looks like it is caused by this code block: https://github.com/yasirkula/SimplePatchTool/blob/23b8f402cb849c432977ff13f0bdb1341bb2d922/SimplePatchToolCore/Other/PatchDownloadManager.cs#L103-L110

It allows SimplePatchTool to abort a download if the downloaded file's size doesn't match the size of the expected file. I wonder what the values of `totalBytesToReceive` and `downloadHandler.DownloadedFileSize` are here. Can you perhaps add some File.AppendAllText lines there to write these values to a log file, rebuild the project and replace SimplePatchTool.dll in Unity with the updated one?

**Comment by OagDevelop** [comment]
I can't seem to find that file. I am using the Unity Version and that file looks like it is in the standalone one. I am going to try using the SimplePatchTool instead of the UnitySimplePatchTool. I will give the stand alone one a try. Does it still use the patches made from the Unity simple patcher

**Comment by yasirkula** [comment]
UnitySimplePatchTool uses SimplePatchTool as dll. You only need to open SimplePatchTool.sln, make changes to the SimplePatchToolCore project, rebuild that project and move its output dll to UnitySimplePatchTool's DLL directory.

**Comment by OagDevelop** [comment]
![image](https://user-images.githubusercontent.com/29358801/51539874-1403e900-1e23-11e9-9820-2a8f18d9ce99.png)

[Output.txt](https://github.com/yasirkula/UnitySimplePatchTool/files/2783023/Output.txt)

Here is the output file. Thanks again for all this support

**Comment by yasirkula** [comment]
What happens when you comment out that 5-line-long if statement to let the download manager proceed as usual?

**Comment by OagDevelop** [comment]
it takes a few minutes per file but it does get through it. I was able to update and play the application, im just making another patch to confirm that it works over multiple attempts. Would there be any issues with using it without the Verify download size check? If there are no issues with removing that if check, than i think everything will be fine and the issue is resolved for me

**Comment by yasirkula** [comment]
No, there would be no issues. If I can't pinpoint the cause of this issue, I might as well remove that condition, too.

**Comment by OagDevelop** [comment]
Ill be sure to let you know if we run into any issues with those lines removed. we will be doing lots of testing so any problems should come to light

**Comment by OagDevelop** [comment]
We have done some large scale testing and the patcher is holding up great. I think you can remove those lines of code and be fine. Thanks again for all the support.
