### ISSUE TITLE
Self Patcher does not exist.

### ISSUE THREAD

**Issue by Velichkowe** [yasirkula/UnitySimplePatchTool#5]
When it says that everythig is ready and restart now, i click restart now and then.. Self Patcher does now exist.
![image](https://user-images.githubusercontent.com/48436771/58749067-b004c780-8489-11e9-9d87-b830dbe831ad.png)

**Comment by yasirkula** [comment]
You need to [create a self patcher executable](https://github.com/yasirkula/SimplePatchTool/wiki/Creating-Self-Patcher-Executable) and put it inside your project's SelfPatcher directory before you start generating patches. For reference, you can follow the Self Patching App Demo tutorial: https://github.com/yasirkula/UnitySimplePatchTool#selfpatchingappdemo

**Comment by Velichkowe** [comment]
Sorry for the stupid question but so it needs to be just in a Folder in my project or in Folder in Asset?

**Comment by Velichkowe** [comment]
> You need to [create a self patcher executable](https://github.com/yasirkula/SimplePatchTool/wiki/Creating-Self-Patcher-Executable) and put it inside your project's SelfPatcher directory before you start generating patches. For reference, you can follow the Self Patching App Demo tutorial: https://github.com/yasirkula/UnitySimplePatchTool#selfpatchingappdemo

Sorry for the stupid question but so it needs to be just in a Folder in my project or in Folder in Asset?

**Comment by yasirkula** [comment]
In the auto-generated "SelfPatcher" folder of your project.

**Comment by Velichkowe** [comment]
okay but i dont understand how to - "rebuild the SelfPatcherWinForms project"

**Comment by Velichkowe** [comment]
> In the auto-generated "SelfPatcher" folder of your project.
okay but i dont understand how to - "rebuild the SelfPatcherWinForms project"

**Comment by Velichkowe** [comment]
> In the auto-generated "SelfPatcher" folder of your project.

okay but i dont understand how to - "rebuild the SelfPatcherWinForms project"

**Comment by yasirkula** [comment]
1. Download the project and unzip it: https://github.com/yasirkula/SimplePatchTool/archive/master.zip
2. Open Extras/SimplePatchToolExtras.sln with Visual Studio
3. Build the SelfPatcherWinForms project

**Comment by Velichkowe** [comment]
Okay i did that and then in i got everything from the Debug folder and moved it in the SelfPatcher folder.
After that i build my game in the Version's subfolder and after that i have to build a patch right but where ?
Am i missing something?

**Comment by Velichkowe** [comment]
> 1. Download the project and unzip it: https://github.com/yasirkula/SimplePatchTool/archive/master.zip
> 2. Open Extras/SimplePatchToolExtras.sln with Visual Studio
> 3. Build the SelfPatcherWinForms project

Okay i did that and then i got everything from the Debug folder and moved it in the SelfPatcher folder.
After that i build my game in the Version's subfolder and after that i have to build a patch right, but where ?
And does that project for the SelfPather has to be in the unity project folder?

Am i missing something?

**Comment by yasirkula** [comment]
Yes, you should build your game into a subdirectory in Versions folder of your project and then generate a patch. Once it finishes, patch files will be located at the Output folder of your project. Self patcher will automatically be included in the patch.

You don't need to add any self patcher files to your Unity project.

**Comment by Velichkowe** [comment]
I think it workes, finally ! Thank you very much for your kindness and fast responding !

**Comment by yasirkula** [comment]
You are welcome 😄
