### ISSUE TITLE
ERROR: file is corrupted

### ISSUE THREAD

**Issue by JesterNovoN** [yasirkula/UnitySimplePatchTool#7]
Greetings.
I'm having an issue in which the patcher download the files just fine but then when it goes and unpack them it says the file is corrupted.

I've had care with the VersionInfo.info file and made sure all the files on the server are public and not behind a login wall.

As a matter of fact the last patch i have generated worked just fine, but now globalgamemanagers.lzdat is always coming out corrupted.

Even though i've tried downloading the file and unpacking it and throwing it in the "_Data" directory and it seems to work just fine.
Repairing doesn't seem to work either.

Any hint on how to fix this?
![image](https://user-images.githubusercontent.com/5576511/63586481-ad55d200-c5a1-11e9-9ccd-8be2846656ca.png)

**Comment by JesterNovoN** [comment]
Nevermind i'm a dumbass.
There was a white space that flew under the radar before the link.
Closing.

**Comment by yasirkula** [comment]
Your launcher looks lovely, awesome!

**Comment by JesterNovoN** [comment]
It's all in the template ;)
