### ISSUE TITLE
Download Links not generating even though BaseDownloadURL is present.

### ISSUE THREAD

**Issue by MisterMan123** [yasirkula/UnitySimplePatchTool#8]
I've been following the guides as close as I can, but even though I set the BaseDownloadURL in my Settings.xml and can see it in my VersionInfo.info, I can't seem to generate the download links with the "Update Download Links" button in the Unity patcher. I've pasted my Settings and VersionInfo below. Using Unity version 2019.1.3f1.

```xml
[redacted]
```

```xml
[redacted]
```

![image](https://user-images.githubusercontent.com/17582887/63645983-1a6b8380-c6d8-11e9-8ec0-776c57d87f51.png)

EDIT: I also just attempted to add a forward slash at the end of the BaseDownloadURL, but results are the same.

**Comment by yasirkula** [comment]
The "Update Download Links" button works with a download links holder file. The process is described here: https://github.com/yasirkula/SimplePatchTool/wiki/Providing-Custom-Download-Links#b-automated-method

When BaseDownloadURL is set, you may not even need to click "Update Download Links". Please see if BaseDownloadURL applies to your server: https://github.com/yasirkula/SimplePatchTool/wiki/Updating-Download-Links-in-VersionInfo#a-using-basedownloadurl

The **Operation successful** message can be misleading here, yes. It basically means that there were no exceptions thrown by the internal UpdateDownloadLinks method. You should take `0/192` message as reference instead.

**Comment by MisterMan123** [comment]
Just so I'm clear, if BaseDownloadURL is set, do the Download URLs also need to be set in the version info? I may have just confused myself.

**Comment by yasirkula** [comment]
If your BaseDownloadURL is e.g. `http://myserver.com/` and you can download your files by appending their paths to this url (e.g. `http://myserver.com/RepairPatch/NetWorld.exe.lzdat` where .lzdat is the repair patch file extension), then **you can leave the per-file download urls blank**. Providing only BaseDownloadURL is sufficient.

P.S. I've tested your BaseDownloadURL, if you add a forward slash at the end, patcher should be able to download files without any issues.

**Comment by MisterMan123** [comment]
Okay, thank you for clearing that up for me. Will go ahead and close this now.
